# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'b19353f1-80d5-40b4-abbe-3f3da4309b54'
  imageRepository: 'ecommerce-admin'
  containerRegistry: 'acrk8sprojectecommerce.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'acrk8sprojectecommerce194d-auth'

  # Name of the new namespace being created to deploy the PR changes.
  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: linuxagent  # Cambiar a 'linuxagent' o el nombre correcto de tu pool
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: linuxagent  # Cambiar a 'linuxagent' o el nombre correcto de tu pool
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y git
      displayName: Install Git

    - script: |
        git clone --branch feature/api-gateway https://$(GITHUB_TOKEN)@github.com/ddn-automatization/ecommerce-iac.git
        cd ecommerce-iac/api-gateway/ecommerce-k8s
        sed -i 's/image: acrk8sprojectecommerce.azurecr.io\/ecommerce-admin:.*/image: acrk8sprojectecommerce.azurecr.io\/ecommerce-admin:$(tag)/' ecommerce-admin.yaml
      displayName: Clone repository and update YAML

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-students'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group apiK8sRss --name myCluster
          kubectl apply -f ecommerce-iac/api-gateway/ecommerce-k8s/ecommerce-admin.yaml
      displayName: Deploy to AKS