
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-admin
  namespace: ecommerce
  labels:
    app: ecommerce-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-admin
  template:
    metadata:
      labels:
        app: ecommerce-admin
    spec:
      containers:
        - name: ecommerce-admin
          image: ventana1901/ecommerce-admin:v6
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              value: "pk_test_Y2FwaXRhbC1odW1wYmFjay01NC5jbGVyay5hY2NvdW50cy5kZXYk"
            - name: CLERK_SECRET_KEY
              value: "sk_test_M41hUtSCghLofhQpfdby0kGTY6j06Aa1SpJuC3HVnA"
            - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
              value: "/sign-in"
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
              value: "/"
            - name: DATABASE_URL
              value: "mysql://admin:Pass123.@mysql:3306/ecommerce_db"
            - name: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
              value: "dytwq4xsw"
            - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
              value: "/sign-up"
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
              value: "/"
            - name: CLOUDINARY_PRESET_NAME
              value: "rl1uzqmr"
            - name: FRONTEND_STORE_URL
              value: "http://ecommerce-store:3001"
            - name: STRIPE_API_KEY
              value: 'sk_test_51PO94nBr9QdWwf17VX0iiy5xLxwqs76mEaYkETOxEP1VHUG7qx9xJvm7g4A9PgQZRWWjirc8hhKYP0JxwormvzM10031eQM9yY'
            - name: STRIPE_WEBHOOK_SECRET
              value: "whsec_2e8232ce37563694ff7ab24cc639b87be827081ca5ff366d0faa88c51fe03f59"

---

apiVersion: v1
kind: Service
metadata:
  name: ecommerce-admin
  namespace: ecommerce
spec:
  selector:
    app: ecommerce-admin
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: LoadBalancer